name: "Bug Report"
description: "Report a bug or error you've encountered with the project."
labels: "bug"
body:
  - type: "markdown"
    content: |
      **Describe the bug**
      A clear and concise description of what the bug is.
  - type: "input"
    attributes:
      label: "Steps to reproduce"
      description: "Provide a list of steps to reproduce the issue."
      placeholder: "Step 1, Step 2, ..."
      required: true
  - type: "input"
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      required: true
  - type: "input"
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
  - type: "input"
    attributes:
      label: "Environment"
      description: "Please provide the environment where the issue occurred (e.g. OS version)."
      placeholder: "e.g. Ubuntu 20.04"
  - type: "input"
    attributes:
      label: "Additional context"
      description: "Any other information or context."
