issue_templates:
  - name: "Bug Report"
    about: "Create a report to help us improve the project."
    labels: "bug"
    template: "bug-report.yml"

  - name: "Feature Request"
    about: "Suggest an idea for this project."
    labels: "enhancement"
    template: "feature-request.yml"
