name: Epic
description: A template for creating detailed epics with all necessary information.
title: "[Epic] "
labels: 
  - epic

body:
  - type: markdown
    attributes:
      value: |
        ## Epic

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the objective of this epic, including the broader goals and outcomes expected.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this epic.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### ⚠️ Assignees
        **Note:** Please ensure to assign at least one responsible person to this epic. The epic cannot proceed without an assignee.
