name: "Feature Request"
description: "Suggest an enhancement or new feature you'd like to see."
labels: "enhancement"
body:
  - type: "markdown"
    content: |
      **Is your feature request related to a problem? Please describe.**
      A clear and concise description of what the problem is.
  - type: "input"
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      required: true
  - type: "input"
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions you've considered."
  - type: "input"
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request."
